// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvqzYxRs5qkk3p76bpiGr-9F3OdhqOJ64',
    appId: '1:642523274242:web:b0bf3198ce74fad2a89b1b',
    messagingSenderId: '642523274242',
    projectId: 'flutter-test-4ba97',
    authDomain: 'flutter-test-4ba97.firebaseapp.com',
    storageBucket: 'flutter-test-4ba97.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl_dkSO7ozf07fLlz3XbdAI5YCO0ZpWT4',
    appId: '1:642523274242:android:ad61ad9b8117af7aa89b1b',
    messagingSenderId: '642523274242',
    projectId: 'flutter-test-4ba97',
    storageBucket: 'flutter-test-4ba97.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKtgK4_OzpbXtCzkUZ7YZdVKoc7lZf_II',
    appId: '1:642523274242:ios:6a64bb9a16c99654a89b1b',
    messagingSenderId: '642523274242',
    projectId: 'flutter-test-4ba97',
    storageBucket: 'flutter-test-4ba97.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKtgK4_OzpbXtCzkUZ7YZdVKoc7lZf_II',
    appId: '1:642523274242:ios:6a64bb9a16c99654a89b1b',
    messagingSenderId: '642523274242',
    projectId: 'flutter-test-4ba97',
    storageBucket: 'flutter-test-4ba97.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

}